version: 1
git_protocol: https
editor:
prompt: enabled
prefer_editor_prompt: disabled
pager:
aliases:
  # --- General Shortcuts ---
  co: pr checkout
  prs: '!gh pr list --author "@me" --state all --json "title,url,updatedAt" --jq ".[] | \"\u001b[38;5;84m\(.title)\u001b[0m \u001b[38;5;117m➜\u001b[0m \u001b[38;5;242m\(.url)\u001b[0m\""'
  open: repo view --web

  # --- Present (Current Activity) ---
  today: '!bash "$HOME/.config/gh/scripts/commits-day.sh" today'
  today-summary: '!bash "$HOME/.config/gh/scripts/commits-day-summary.sh" today'
  today-stats: '!bash "$HOME/.config/gh/scripts/run-stats.sh" today'
  this-month-summary: '!bash "$HOME/.config/gh/scripts/run-summary.sh" month'
  this-month-stats: '!bash "$HOME/.config/gh/scripts/run-stats.sh" month'
  this-year-summary: '!bash "$HOME/.config/gh/scripts/run-summary.sh" year'
  this-year-stats: '!bash "$HOME/.config/gh/scripts/run-stats.sh" year'

  # --- Past (Historical Activity) ---
  yesterday: '!bash "$HOME/.config/gh/scripts/commits-day.sh" yesterday'
  yesterday-summary: '!bash "$HOME/.config/gh/scripts/commits-day-summary.sh" yesterday'
  yesterday-stats: '!bash "$HOME/.config/gh/scripts/run-stats.sh" yesterday'
  last-month-summary: '!bash "$HOME/.config/gh/scripts/run-summary.sh" last-month'
  last-month-stats: '!bash "$HOME/.config/gh/scripts/run-stats.sh" last-month'
  last-year-summary: '!bash "$HOME/.config/gh/scripts/run-summary.sh" last-year'
  last-year-stats: '!bash "$HOME/.config/gh/scripts/run-stats.sh" last-year'

  # --- Insights & Streak ---
  this-year-languages: '!bash "$HOME/.config/gh/scripts/run-languages.sh" year'
  last-year-languages: '!bash "$HOME/.config/gh/scripts/run-languages.sh" last-year'
  streak: '!bash "$HOME/.config/gh/scripts/run-streak.sh"'

http_unix_socket:
browser:
color_labels: enabled
accessible_colors: disabled
accessible_prompter: disabled
spinner: enabled
