## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░
## CROSS-SHELL PROMPT
## The minimal, blazing-fast, and infinitely customizable prompt for anyshell!

format = """
$hostname\
$directory\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$hg_branch\
$docker_context\
$package\
$nodejs\
$python\
$golang\
$rust\
$java\
$julia\
$elixir\
$elm\
$haskell\
$nim\
$nix_shell\
$perl\
$php\
$ruby\
$scala\
$swift\
$dart\
$conda\
$aws\
$c\
$cpp\
$lua\
$kotlin\
$ocaml\
$zig\
$deno\
$bun\
$crystal\
$fennel\
$fortran\
$gradle\
$guix_shell\
$haxe\
$meson\
$pixi\
$rlang\
$xmake\
$buf\
$cmake\
$gcloud\
$memory_usage\
$custom\
$sudo\
$fill\
$git_branch\
$git_status\
$git_commit\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$line_break\
$character"""

# Disable the blank line at the start of the prompt
add_newline = true

# Second param
[hostname]
ssh_only = true
format = "[](fg:#252525 bg:none)[█](fg:#E8E3E3 bg:#252525)[$ssh_symbol$hostname](bold bg:#E8E3E3)[](fg:#E8E3E3 bg:none) "
disabled = false

# Third param
[directory]
format = "[](fg:#252525 bg:none)[$path]($style)[█](fg:#232526 bg:#232526)[](fg:#68f7d8 bg:#252525)[ ](fg:#252525 bg:#68f7d8)[](fg:#68f7d8 bg:none)"
style = "fg:#E8E3E3 bg:#252525 bold"
truncation_length = 1
truncate_to_repo=false
read_only = " 󰌾"


## SECOND LINE/ROW: Prompt
# Prompt: param 2 └─
[character]
success_symbol = "[ ](#68f7d8 bold)"
error_symbol = "[ ](#B66467 bold)"

[line_break]
disabled = false

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
min_time = 1
format = "[](fg:#252525 bg:none)[$duration]($style)[](fg:#252525 bg:#252525)[](fg:#C397D8 bg:#252525)[󱑂 ](fg:#252525 bg:#C397D8)[](fg:#C397D8 bg:none)"
disabled = false
style = "fg:#E8E3E3 bg:#252525 bold"


[git_branch]
format = "[](fg:#252525 bg:none)[$branch]($style)[](fg:#252525 bg:#252525)[](fg:#81C19B bg:#252525)[](fg:#252525 bg:#81C19B)[](fg:#81C19B bg:none) "
style = "fg:#E8E3E3 bg:#252525"
symbol = " "

[git_status]
format="[](fg:#252525 bg:none)[$all_status$ahead_behind]($style)[](fg:#252525 bg:#252525)[](fg:#68f7d8 bg:#252525)[ ](fg:#252525 bg:#68f7d8)[](fg:#68f7d8 bg:none) "
style = "fg:#E8E3E3 bg:#252525"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = " 󰄸 "
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = " ${count}"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge =	"MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style =	"yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '


# # SYMBOLS

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

# [directory]

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "bold yellow"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[status]
symbol = " "

[swift]
symbol = " "

[xmake]
symbol = " "

[zig]
symbol = " "

[custom.vscode]
command = """
for bin in code-insiders code-oss code; do
  path=$(command -v $bin 2>/dev/null) || continue
  real=$(readlink -f $path 2>/dev/null || echo $path)
  dir=$(dirname $real)
  pkg="$dir/../resources/app/package.json"
  if [ -f "$pkg" ]; then
    grep -m1 '\"version\"' \"$pkg\" | sed 's/.*\"version\": *\"\\(.*\\)\".*/v\\1/' | tr -d '\\n'
    break
  fi
done
"""
symbol = " 󰨞 "
format = "[$symbol$output]($style) "
style = "fg:#23A9F2 bold"
when = "command -v code &>/dev/null || command -v code-oss &>/dev/null || command -v code-insiders &>/dev/null"
detect_folders = ["."]
shell = ["bash", "--noprofile", "--norc"]